FB_SESSION = {'uid': '1900847', 'access_token': '303546531451|2.2d_tPG4z31mUljJ7gjKDWg__.3600.1277841600-1900847|BFH81UtwPT9fOnA0pBYQ9gaA_ag.', 'expires': '1277841600', 'base_domain': 'seddit.com', 'secret': 'HZ_Q_1Eirob4og3dfUcuaA__', 'sig': '2d5073076a207c2634a013c44b32ca54', 'session_key': '2.2d_tPG4z31mUljJ7gjKDWg__.3600.1277841600-1900847'}

FB_INFO = {u'first_name': u'Andrew', u'last_name': u'Badr', u'verified': True, u'name': u'Andrew Badr', u'locale': u'en_US', u'hometown': {u'id': 106220079409935L, u'name': u'Nashville, Tennessee'}, u'updated_time': u'2010-06-28T22:12:52+0000', u'religion': u'The universe is a pot of water boiling over.', u'birthday': u'03/04/1984', u'link': u'http://www.facebook.com/reverie', u'location': {u'id': 108363292521622L, u'name': u'Oakland, California'}, u'gender': u'male', u'timezone': -7, u'education': [{u'school': {u'id': 109569892401978L, u'name': u'University School of Nashville'}, u'year': {u'id': 110778035616279L, u'name': u'2002'}}, {u'school': {u'id': 163536409904L, u'name': u'University of Illinois at Urbana-Champaign'}, u'concentration': [{u'id': 113035942055350L, u'name': u'Computer Science'}], u'year': {u'id': 114730105211023L, u'name': u'2006'}}], u'id': u'1900847'}

FB_NULL_LOC_INFO = {u'first_name': u'Will', u'last_name': u'Tsui', u'verified': True, u'name': u'Will Tsui', u'locale': u'en_US', u'hometown': {u'id': None, u'name': None}, u'updated_time': u'2010-01-09T23:09:32+0000', u'link': u'http://www.facebook.com/wtsui', u'location': {u'id': None, u'name': None}, u'gender': u'male', u'timezone': -7, u'id': u'305435'}

TWITTER_USER_INFO = {'contributors_enabled': False,
                       'created_at': 'Mon Jun 02 23:23:24 +0000 2008',
                       'description': '',
                       'favourites_count': 0,
                       'follow_request_sent': False,
                       'followers_count': 256,
                       'following': False,
                       'friends_count': 87,
                       'geo_enabled': False,
                       'id': 14986550,
                       'lang': 'en',
                       'location': 'Oakland, CA',
                       'name': 'Andrew Badr',
                       'notifications': False,
                       'profile_background_color': 'CCB29D',
                       'profile_background_image_url': 'http://a1.twimg.com/profile_background_images/58484136/x577f22a2c276e7e62f667bc7c87d552.png',
                       'profile_background_tile': True,
                       'profile_image_url': 'http://a3.twimg.com/profile_images/994663039/photo_normal.jpeg',
                       'profile_link_color': '5A5D63',
                       'profile_sidebar_border_color': '3E424F',
                       'profile_sidebar_fill_color': 'EBEBEB',
                       'profile_text_color': '0F0F0F',
                       'profile_use_background_image': True,
                       'protected': False,
                       'screen_name': 'andrewbadr',
                       'status': {'contributors': None,
                                  'coordinates': None,
                                  'created_at': 'Fri Jul 16 00:28:14 +0000 2010',
                                  'favorited': False,
                                  'geo': None,
                                  'id': 18643334651L,
                                  'in_reply_to_screen_name': 'twitter',
                                  'in_reply_to_status_id': None,
                                  'in_reply_to_user_id': 783214,
                                  'place': None,
                                  'source': '<a href="http://www.tweetdeck.com" rel="nofollow">TweetDeck</a>',
                                  'text': '@twitter http://dev.twitter.com/pages/oauth_libraries  should maybe point to the simplegeo fork of python-oauth2, as that is used on pypi',
                                  'truncated': False},
                       'statuses_count': 610,
                       'time_zone': 'Pacific Time (US & Canada)',
                       'url': 'http://ianab.com/',
                       'utc_offset': -28800,
                       'verified': False}
