#!/usr/bin/env python
import sys

def usage():
    print "Usage: %s <release_dir>" % (sys.argv[0])
    sys.exit(1)

def main():
    # Validation and testing assumptions:
    if len(sys.argv) != 2:
        usage()
    release_dir = sys.argv[1]
    # Put your own here...
    return 

if __name__ == '__main__':
    main()
